front/app/routes/auth.py
from flask import Blueprint, request, session, redirect
from flask import url_for, flash, render_template
import requests
from app import utilidades

auth_bp = Blueprint('auth', __name__)

@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        # Send login request to FastAPI app
        login_data = {"username": username, "password": password}
        url_router = f"{utilidades.API_URL}/login"
        try:
            response = requests.post(url_router, json=login_data)
            if response.status_code == 200:
                data = response.json()
                session["username"] = username
                session["access_token"] = data["access_token"]
                session['profile_image_url'] = None                
                return redirect(url_for("dashboard.dashboard"))
            elif response.status_code == 401: 
                error_message = "401 Unauthorized for invalid credentials"                             
            else:
                error_message = "Invalid username or password"
        except requests.exceptions.MissingSchema:
            error_message = f"URL {utilidades.API_URL}/login inválida"
        except requests.exceptions.ConnectionError:
            error_message = "Erro de conexão na tentativa do login"
        except IOError: 
            error_message = "Erro de IO durante o login"
        flash(error_message, category='danger')

        return render_template("auth/login.html")

    return render_template("auth/login.html")

# Pagina de registro
@auth_bp.route("/register", methods=['GET', 'POST'])
def register():
    """
    Register a new user.
    Validates that the username is not already taken. Hashes the password for security.
    """
    if request.method == "POST":
        name = request.form["name"]
        username = request.form["username"]
        email = request.form["email"]
        password = request.form["password"]
        repassword = request.form["repassword"]
        
        error_message = None

        if not username:
            error_message = "Username is required."
        elif not email: 
            error_message = "E-mail is required."
        elif not password:
            error_message = "Password is required."
        elif password != repassword: 
            error_message = "Password is not correct."

        if error_message is None:
            try: 
                # Send user data to FastAPI app
                user_data = {"id": 0, "username": username, "email":email, "password": password}
                url_router = f"{utilidades.API_URL}/users"
                response = requests.post(url_router, json=user_data)
                if response.status_code == 200:
                    mensagem = f"Usuário {username} criado com sucesso!"
                    flash(mensagem, category='success')
                    return redirect(url_for("auth.login"))
                else: 
                    error_message = f"User {username} is already registered."
                
            except requests.exceptions.MissingSchema:
                error_message = f"URL {utilidades.API_URL}/users inválida"
            except requests.exceptions.ConnectionError:
                error_message = "Erro de conexão na tentativa do login"
            except IOError: 
                error_message = "Erro de IO durante o login"
        
        flash(error_message, category='danger')                
        return render_template("auth/register.html", error_message=error_message)
    return render_template("auth/register.html")

# Pagina de recuperacao de e-mail
@auth_bp.route("/forgot-password", methods=["GET"])
def forgot():
    return render_template("auth/forgot-password.html")

@auth_bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("auth.login"))

front/app/routes/dashboard.py
from flask import Blueprint, request, session, redirect
from flask import url_for, flash, render_template
import requests
from app import utilidades
from app import dto
import json
import plotly.express as px
import pandas as pd

dashboard_bp = Blueprint('dashboard', __name__)

@dashboard_bp.route("/dashboard")
def dashboard():
    if "username" not in session:
        return redirect(url_for("auth.login"))

    try:
        # Retrieve user information from FastAPI app using token
        access_token = session["access_token"] 
        headers = {"Authorization": f"Bearer {access_token}"}
        usuario_logado = session['username']
        url_router = f"{utilidades.API_URL}/users/{usuario_logado}"
        response = requests.get(url_router, headers=headers)
    
        if response.status_code == 200:
            user_data = response.json()            
            url_route_profile = f"{utilidades.API_URL}/users/{usuario_logado}/profile"
            response_profile = requests.get(url_route_profile, headers=headers)

            if response_profile.status_code == 200:
                user_data_profile = response_profile.json()
                session['profile_image_url'] = user_data_profile['profile_image_url']
                
            return render_template("dashboard/starter.html", user=user_data, usuario = usuario_logado, 
                profilePic=session['profile_image_url'], titulo="Dashboard")

        else:
            # Handle error retrieving user information
            error_message = f"Failed to retrieve user information - {response.status_code}"
            return render_template("error.html", message=error_message)

    except requests.exceptions.MissingSchema:
        error_message = f"URL {url_router} inválida"
    except requests.exceptions.ConnectionError:
        error_message = "Erro de conexão"
    except IOError: 
        error_message = "Erro de IO"    
    except Exception as ex:
        error_message = f"Erro: {str(ex)}"
    flash(error_message, category='danger')

    return render_template("auth/login.html", error_message=error_message)

@dashboard_bp.route("/dashboard/my_notes")
def my_notes():
    if "username" not in session:
        return redirect(url_for("auth.login"))

    try:
        # Retrieve user information from FastAPI app using token
        access_token = session["access_token"] 
        headers = {"Authorization": f"Bearer {access_token}"}
        usuario_logado = session['username']
        url_router = f"{utilidades.API_URL}/users/{usuario_logado}"
        response = requests.get(url_router, headers=headers)
    
        if response.status_code == 200:
            user_data = response.json()            
            url_route_profile = f"{utilidades.API_URL}/users/{usuario_logado}/profile"
            url_route_all_notes = f"{utilidades.API_URL}/users/{usuario_logado}/notes"
            
            response_profile = requests.get(url_route_profile, headers=headers)
            response_all_notes = requests.get(url_route_all_notes, headers=headers)

            if response_profile.status_code == 200:
                user_data_profile = response_profile.json()
                session['profile_image_url'] = user_data_profile['profile_image_url']
                
            if response_all_notes.status_code == 200:
                notes_data = response_all_notes.json()
                dadosDashboardDTO = dto.DadosDashboardDTO(lista_usuarios=[], lista_imagens=[], lista_analises=[], lista_notas=notes_data)

            return render_template("dashboard/my_notes.html", user=user_data, usuario = usuario_logado, 
                profilePic=session['profile_image_url'], titulo="Dashboard",dadosDashboardDTO=dadosDashboardDTO)

        else:
            # Handle error retrieving user information
            error_message = f"Failed to retrieve user information - {response.status_code}"
            return render_template("error.html", message=error_message)

    except requests.exceptions.MissingSchema:
        error_message = f"URL {url_router} inválida"
    except requests.exceptions.ConnectionError:
        error_message = "Erro de conexão"
    except IOError: 
        error_message = "Erro de IO"    
    except Exception as ex:
        error_message = f"Erro: {str(ex)}"
    flash(error_message, category='danger')

    return render_template("auth/login.html", error_message=error_message)

@dashboard_bp.route("/dashboard/my_time")
def my_time():
    if "username" not in session:
        return redirect(url_for("auth.login"))

    try:
        # Retrieve user information from FastAPI app using token
        access_token = session["access_token"] 
        headers = {"Authorization": f"Bearer {access_token}"}
        usuario_logado = session['username']
        url_router = f"{utilidades.API_URL}/users/{usuario_logado}"
        response = requests.get(url_router, headers=headers)
    
        if response.status_code == 200:
            user_data = response.json()            
            url_route_profile = f"{utilidades.API_URL}/users/{usuario_logado}/profile"
            
            response_profile = requests.get(url_route_profile, headers=headers)
            response_my_time = requests.get(utilidades.url_servico_mytime)

            if response_profile.status_code == 200:
                user_data_profile = response_profile.json()
                session['profile_image_url'] = user_data_profile['profile_image_url']
                
            if response_my_time.status_code == 200:
                data = response_my_time.json()
                json_data = json.loads(data)
                df = pd.DataFrame(json_data)
                fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task")
                fig.update_yaxes(autorange="reversed")

            return render_template("dashboard/my_time.html", user=user_data, usuario = usuario_logado, 
                profilePic=session['profile_image_url'], titulo="Dashboard", graphJSON=fig.to_json())

        else:
            # Handle error retrieving user information
            error_message = f"Failed to retrieve user information - {response.status_code}"
            return render_template("error.html", message=error_message)

    except requests.exceptions.MissingSchema:
        error_message = f"URL {url_router} inválida"
    except requests.exceptions.ConnectionError:
        error_message = "Erro de conexão"
    except IOError: 
        error_message = "Erro de IO"    
    except Exception as ex:
        error_message = f"Erro: {str(ex)}"
    flash(error_message, category='danger')

    return render_template("auth/login.html", error_message=error_message)

front/templates/dashboard/my_notes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <header class="navbar sticky-top container-fluid d-flex flex-wrap align-items-center justify-content-between py-1 bg-light">
        <h1 class="fs-4">{{ titulo }}</h1>
        <div class="d-flex align-items-center">
            <img src="{{ profilePic }}" alt="Profile Picture" class="me-3 img-thumbnail rounded-circle" style="width: 40px; height: 40px;">
            <span class="text-muted">{{ user.username }}</span>
            <a href="{{ url_for('auth.logout') }}" class="btn btn-sm btn-outline-primary ms-3">Sair</a>
        </div>
        <div class="container-fluid">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb p-1 bg-body-tertiary rounded-3">
                  <li class="breadcrumb-item"><a href="{{ url_for('dashboard.dashboard') }}">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Anotações</li>
                </ol>
            </nav>
        </div>    
    </header>
    <div class="container-fluid">   
        <div class="row">
            <div class="sidebar col-md-3 col-lg-2 p-1 bg-light">
              <ul class="nav flex-column">
                <li class="nav-item">
                  <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{{ url_for('dashboard.my_notes')}}">
                    Anotações
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link d-flex align-items-center gap-2" href="{{ url_for('dashboard.my_time') }}">
                    My Time
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link d-flex align-items-center gap-2" href="#">
                    My Plot
                  </a>
                </li>
              </ul>
            </div>
            <main class="col-md-9 col-lg-10">
              <div>
                    <h4>Anotações</h4>
                    <ul class="list-group">
                        {% for note in dadosDashboardDTO.lista_notas %}
                            <li class="list-group-item">{{ note }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </main>
        </div>
    </div>

</body>
</html>

front/templates/dashboard/my_time.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <header class="navbar sticky-top container-fluid d-flex flex-wrap align-items-center justify-content-between py-1 bg-light">
        <h1 class="fs-4">{{ titulo }}</h1>
        <div class="d-flex align-items-center">
            <img src="{{ profilePic }}" alt="Profile Picture" class="me-3 img-thumbnail rounded-circle" style="width: 40px; height: 40px;">
            <span class="text-muted">{{ user.username }}</span>
            <a href="{{ url_for('auth.logout') }}" class="btn btn-sm btn-outline-primary ms-3">Sair</a>
        </div>
        <div class="container-fluid">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb p-1 bg-body-tertiary rounded-3">
                  <li class="breadcrumb-item"><a href="{{ url_for('dashboard.dashboard') }}">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">My Time</li>
                </ol>
            </nav>
        </div>    
    </header>
    <div class="container-fluid">   
        <div class="row">
            <div class="sidebar col-md-3 col-lg-2 p-1 bg-light">
              <ul class="nav flex-column">
                <li class="nav-item">
                  <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{{ url_for('dashboard.my_notes')}}">
                    Anotações
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link d-flex align-items-center gap-2" href="{{ url_for('dashboard.my_time') }}">
                    My Time
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link d-flex align-items-center gap-2" href="#">
                    My Plot
                  </a>
                </li>
              </ul>
            </div>
            <main class="col-md-9 col-lg-10">
              <div>
                    <h4>My Time</h4>
                    <div id="graph1"></div>
                    <script>
                        var graph1 = {{ graphJSON | safe }};
                        Plotly.newPlot('graph1', graph1);
                    </script>                
                </div>
            </main>
        </div>
    </div>

</body>
</html>

front/templates/dashboard/starter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <header class="navbar sticky-top container-fluid d-flex flex-wrap align-items-center justify-content-between py-1 bg-light">
        <h1 class="fs-4">{{ titulo }}</h1>
        <div class="d-flex align-items-center">
            <img src="{{ profilePic }}" alt="Profile Picture" class="me-3 img-thumbnail rounded-circle" style="width: 40px; height: 40px;">
            <span class="text-muted">{{ user.username }}</span>
            <a href="{{ url_for('auth.logout') }}" class="btn btn-sm btn-outline-primary ms-3">Sair</a>
        </div>
        <div class="container-fluid">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb p-1 bg-body-tertiary rounded-3">
                  <li class="breadcrumb-item "><a href="{{ url_for('dashboard.dashboard') }}">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Funcionalidades</li>
                </ol>
            </nav>
        </div>    
    </header>
    <div class="container-fluid">   
        <div class="row">
            <div class="sidebar col-md-3 col-lg-2 p-1 bg-light">
                <ul class="nav flex-column">
                    <li class="nav-item">
                      <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{{ url_for('dashboard.my_notes')}}">
                        Anotações
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link d-flex align-items-center gap-2" href="{{ url_for('dashboard.my_time') }}">
                        My Time
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link d-flex align-items-center gap-2" href="#">
                        My Plot
                      </a>
                    </li>
                  </ul>
            </div>
            <main class="col-md-9 col-lg-10">
                <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
                    <div class="feature col">
                      <h3 class="fs-2 text-body-emphasis">Anotações</h3>
                      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
                      <a href="#" class="icon-link">
                        Call to action
                      </a>
                    </div>
                    <div class="feature col">
                      <h3 class="fs-2 text-body-emphasis">My Time</h3>
                      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
                      <a href="#" class="icon-link">
                        Call to action
                      </a>
                    </div>
                    <div class="feature col">
                      <h3 class="fs-2 text-body-emphasis">My Plot</h3>
                      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
                      <a href="#" class="icon-link">
                        Call to action
                      </a>
                    </div>
              </div>

            </main>
        </div>
    </div>

</body>
</html>